# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setMinimumSize(QtCore.QSize(800, 600))
        MainWindow.setMaximumSize(QtCore.QSize(800, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lineEdit_barcode = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_barcode.setGeometry(QtCore.QRect(40, 60, 491, 21))
        self.lineEdit_barcode.setObjectName("lineEdit_barcode")
        self.lineEdit_gtin = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_gtin.setGeometry(QtCore.QRect(40, 170, 301, 21))
        self.lineEdit_gtin.setObjectName("lineEdit_gtin")
        self.lineEdit_serial = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_serial.setGeometry(QtCore.QRect(40, 270, 301, 21))
        self.lineEdit_serial.setObjectName("lineEdit_serial")
        self.lineEdit_expire = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_expire.setGeometry(QtCore.QRect(40, 370, 211, 21))
        self.lineEdit_expire.setObjectName("lineEdit_expire")
        self.pushButton_ok = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_ok.setGeometry(QtCore.QRect(600, 470, 101, 32))
        self.pushButton_ok.setObjectName("pushButton_ok")
        self.pushButton_decode = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_decode.setGeometry(QtCore.QRect(600, 50, 101, 32))
        self.pushButton_decode.setObjectName("pushButton_decode")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        self.menuDatei = QtWidgets.QMenu(self.menubar)
        self.menuDatei.setObjectName("menuDatei")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionBeenden = QtWidgets.QAction(MainWindow)
        self.actionBeenden.setObjectName("actionBeenden")
        self.action_ber_Barcode_Leser = QtWidgets.QAction(MainWindow)
        self.action_ber_Barcode_Leser.setObjectName("action_ber_Barcode_Leser")
        self.menuDatei.addAction(self.actionBeenden)
        self.menu.addAction(self.action_ber_Barcode_Leser)
        self.menubar.addAction(self.menuDatei.menuAction())
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Barcode-Leser"))
        self.pushButton_ok.setText(_translate("MainWindow", "Fertig"))
        self.pushButton_decode.setText(_translate("MainWindow", "Lesen"))
        self.menuDatei.setTitle(_translate("MainWindow", "Datei"))
        self.menu.setTitle(_translate("MainWindow", "?"))
        self.actionBeenden.setText(_translate("MainWindow", "Beenden"))
        self.action_ber_Barcode_Leser.setText(_translate("MainWindow", "Über Barcode-Leser"))
