# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(60, 50, 291, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(280, 260, 101, 32))
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Info"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Dieses Programm dient dem Lesen von Barcodes der Implantate für die Pflege der Endoprothesen-Stammdaten. Es wird die Implantate-json-Datei für die Ermittlung von REF-Nummern bzw. Validierung der GTIN eingebunden. Verwendet wurden die Sprachen PyQT5 und Python.\n"
"\n"
"Brady"))
        self.pushButton_ok.setText(_translate("Dialog", "Fertig"))
