# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'info_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        Dialog.setMinimumSize(QtCore.QSize(400, 300))
        Dialog.setMaximumSize(QtCore.QSize(400, 300))
        self.plainTextEdit = QtWidgets.QPlainTextEdit(Dialog)
        self.plainTextEdit.setGeometry(QtCore.QRect(50, 40, 291, 191))
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.pushButton_ok = QtWidgets.QPushButton(Dialog)
        self.pushButton_ok.setGeometry(QtCore.QRect(280, 260, 101, 32))
        self.pushButton_ok.setObjectName("pushButton_ok")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Info"))
        self.plainTextEdit.setPlainText(_translate("Dialog", "Der Barcode-Leser ist eine Desktop-Anwendung, die mit PyQt5 entwickelt wurde und es Benutzern ermöglicht, Barcode-Daten einzugeben und zu verarbeiten. Die Anwendung kann verschiedene Barcode-Informationen wie GTIN, Seriennummern, Referenznummern und Ablaufdaten extrahieren und anzeigen.\n"
"\n"
"(C) 2025 Brady"))
        self.pushButton_ok.setText(_translate("Dialog", "Fertig"))
