# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'file_open.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FileOpenDialog(object):
    def setupUi(self, FileOpenDialog):
        FileOpenDialog.setObjectName("FileOpenDialog")
        FileOpenDialog.resize(600, 240)
        FileOpenDialog.setModal(True)
        self.mainLayout = QtWidgets.QVBoxLayout(FileOpenDialog)
        self.mainLayout.setObjectName("mainLayout")
        self.pathLayout = QtWidgets.QHBoxLayout()
        self.pathLayout.setObjectName("pathLayout")
        self.pathLabel = QtWidgets.QLabel(FileOpenDialog)
        self.pathLabel.setMinimumSize(QtCore.QSize(40, 0))
        self.pathLabel.setObjectName("pathLabel")
        self.pathLayout.addWidget(self.pathLabel)
        self.pathLineEdit = QtWidgets.QLineEdit(FileOpenDialog)
        self.pathLineEdit.setReadOnly(True)
        self.pathLineEdit.setObjectName("pathLineEdit")
        self.pathLayout.addWidget(self.pathLineEdit)
        self.browseButton = QtWidgets.QPushButton(FileOpenDialog)
        self.browseButton.setMinimumSize(QtCore.QSize(100, 30))
        self.browseButton.setObjectName("browseButton")
        self.pathLayout.addWidget(self.browseButton)
        self.mainLayout.addLayout(self.pathLayout)
        self.filterGroupBox = QtWidgets.QGroupBox(FileOpenDialog)
        self.filterGroupBox.setObjectName("filterGroupBox")
        self.filterLayout = QtWidgets.QVBoxLayout(self.filterGroupBox)
        self.filterLayout.setObjectName("filterLayout")
        self.filterComboBox = QtWidgets.QComboBox(self.filterGroupBox)
        self.filterComboBox.setObjectName("filterComboBox")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterComboBox.addItem("")
        self.filterLayout.addWidget(self.filterComboBox)
        self.mainLayout.addWidget(self.filterGroupBox)
        self.buttonLayout = QtWidgets.QHBoxLayout()
        self.buttonLayout.setObjectName("buttonLayout")
        self.statusLabel = QtWidgets.QLabel(FileOpenDialog)
        self.statusLabel.setObjectName("statusLabel")
        self.buttonLayout.addWidget(self.statusLabel)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.buttonLayout.addItem(spacerItem)
        self.openButton = QtWidgets.QPushButton(FileOpenDialog)
        self.openButton.setEnabled(False)
        self.openButton.setMinimumSize(QtCore.QSize(80, 30))
        self.openButton.setDefault(True)
        self.openButton.setObjectName("openButton")
        self.buttonLayout.addWidget(self.openButton)
        self.cancelButton = QtWidgets.QPushButton(FileOpenDialog)
        self.cancelButton.setMinimumSize(QtCore.QSize(80, 30))
        self.cancelButton.setObjectName("cancelButton")
        self.buttonLayout.addWidget(self.cancelButton)
        self.mainLayout.addLayout(self.buttonLayout)

        self.retranslateUi(FileOpenDialog)
        self.cancelButton.clicked.connect(FileOpenDialog.reject) # type: ignore
        self.openButton.clicked.connect(FileOpenDialog.accept) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(FileOpenDialog)

    def retranslateUi(self, FileOpenDialog):
        _translate = QtCore.QCoreApplication.translate
        FileOpenDialog.setWindowTitle(_translate("FileOpenDialog", "Datei öffnen"))
        self.pathLabel.setText(_translate("FileOpenDialog", "Pfad:"))
        self.pathLineEdit.setPlaceholderText(_translate("FileOpenDialog", "Kein Pfad ausgewählt"))
        self.browseButton.setText(_translate("FileOpenDialog", "Durchsuchen..."))
        self.filterGroupBox.setTitle(_translate("FileOpenDialog", "Dateifilter"))
        self.filterComboBox.setItemText(0, _translate("FileOpenDialog", "Alle Dateien (*.*)"))
        self.filterComboBox.setItemText(1, _translate("FileOpenDialog", "Textdateien (*.txt)"))
        self.filterComboBox.setItemText(2, _translate("FileOpenDialog", "Python-Dateien (*.py)"))
        self.filterComboBox.setItemText(3, _translate("FileOpenDialog", "JSON-Dateien (*.json)"))
        self.filterComboBox.setItemText(4, _translate("FileOpenDialog", "CSV-Dateien (*.csv)"))
        self.statusLabel.setStyleSheet(_translate("FileOpenDialog", "color: gray;"))
        self.statusLabel.setText(_translate("FileOpenDialog", "Bereit"))
        self.openButton.setText(_translate("FileOpenDialog", "Öffnen"))
        self.cancelButton.setText(_translate("FileOpenDialog", "Abbrechen"))
